trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm test
  env:
    ASKUI_WORKSPACE_ID: $(ASKUI_WORKSPACE_ID)
    ASKUI_TOKEN: $(ASKUI_TOKEN)
    ASKUI_INFERENCE_SERVER_URL: $(ASKUI_INFERENCE_SERVER_URL)
  displayName: 'npm build'

# TODO
# Where to store the history?
# Generate the allure report from the allure-result directory
# Publish it with Allure Test Reports?
