# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  - job: RunAskUI
    continueOnError: true
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'Install Node.js'
      - bash: |
          echo 'Run npm install'
          npm install
          echo 'Run AskUI'
          npm run test
        displayName: 'Run AskUI'
  - job: GenerateAllureReport
    pool:
      vmImage: ubuntu-latest
    container:
      pradapjackie/allure-reports-generation:1.0
    steps:
      - bash: |
          allure generate allure-results -o allure-report
          mv allure-report history
      # Install https://github.com/mclay/azure-pipeline-allure-report first
      - task: PublishAllureReport@1
        displayName: 'Publish Allure Report'
        inputs:
          reportDir: 'history'
